name: PiPy
on:
  push:
    tags:
      - 'v*'
jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    needs: release
    env:
      POWERLINEK8SSTATUS_VERSION: ${{ github.event.release.tag_name }}
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_APIKEY }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Publish to PyPI
      run: |
        make build
